#!/bin/bash

function is_missing() {
  if ! command -v -- "$1" > /dev/null 2>&1; then
    return 0
  fi
  return 1
}
if is_missing cargo; then
  echo "missing cargo"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -- -y
fi