[v1]
"atuin 18.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["atuin.exe"]
"avm 0.29.0 (git+https://github.com/coral-xyz/anchor#ef836852dd44e916f5284fc0b8c764c7e856ae0c)" = [
    "anchor.exe",
    "avm.exe",
]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat.exe"]
"bottom 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm.exe"]
"cargo-update 13.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update-config.exe",
    "cargo-install-update.exe",
]
"create-tauri-app 3.13.17 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-create-tauri-app.exe"]
"dioxus-cli 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dx.exe"]
"dotter 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dotter.exe"]
"eza 0.18.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza.exe"]
"fend 1.4.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["fend.exe"]
"git-cliff 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff-completions.exe",
    "git-cliff-mangen.exe",
    "git-cliff.exe",
]
"grex 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex.exe"]
"hyperfine 1.18.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine.exe"]
"just 1.25.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["just.exe"]
"krabby 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["krabby.exe"]
"macchina 6.1.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["macchina.exe"]
"oxker 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["oxker.exe"]
"starship 1.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship.exe"]
"tauri-cli 2.0.0-beta.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tauri.exe"]
"trunk 0.19.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk.exe"]
"zoxide 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide.exe"]
