[helpers]

[default]
depends = ["shell", "cargo", "bash", "zsh"]

[default.files]
".glaze-wm/" = "~/.glaze-wm/"
".glzr/zebar/" = { type = "symbolic", target = "~/.glzr/zebar/" }

[default.variables]

[shell.files]
".config/starship.toml" = "~/.config/starship.toml"
"gitconfigs/.gitconfig" = "~/.gitconfig"
"gitconfigs/.gitconfig-personal" = "~/.gitconfig-personal"
"gitconfigs/.gitconfig-work" = "~/.gitconfig-work"
"atuin.toml" = { type = "symbolic", target = "~/.config/atuin/config.toml", if = '(is_executable "atuin")' }

[bash]
depends = ["shell"]

[bash.files]
".bashrc" = "~/.bashrc"

[zsh]
depends = ["shell"]

[zsh.files]
".zshrc" = "~/.zshrc"

[cargo]

[cargo.files]
".cargo/.crates.toml" = "~/.cargo/.crates.toml"
".cargo/.crates2.json" = "~/.cargo/.crates2.json"
