[helpers]

[default]
depends = ["shell", "zsh", "cargo", "glazewm"]

[glazewm]
[glazewm.files]
".glaze-wm/" = { target = "~/.glaze-wm/", type="symbolic", if="(eq dotter.os 'Windows')" }
".glzr/zebar/" = { target = "~/.glzr/zebar/", type="symbolic", if="(eq dotter.os 'Windows')" }


[default.variables]

[shell.files]
".config/starship.toml" = "~/.config/starship.toml"
"gitconfigs/.gitconfig" = "~/.gitconfig"
"gitconfigs/.gitconfig-personal" = "~/.gitconfig-personal"
"gitconfigs/.gitconfig-work" = "~/.gitconfig-work"
"atuin.toml" = { type = "symbolic", target = "~/.config/atuin/config.toml", if = '(is_executable "atuin")' }

[zsh]
depends = ["shell"]

[zsh.files]
".zshrc" = { target = "~/.zshrc", type = "symbolic" }

[cargo]
[cargo.files]
".cargo/.crates.toml" = "~/.cargo/.crates.toml"
".cargo/.crates2.json" = "~/.cargo/.crates2.json"
